variable "region" {}
variable "profile" {}
variable "red_hat" {}
variable "ubuntu" {}
variable "vpc_cidr" {}
variable "pub-sub1_cidr" {}
variable "pub-sub2_cidr" {}
variable "prv1_cidr" {}
variable "prv2_cidr" {}
variable "az1" {}
variable "az2" {}
variable "cidr_all" {}
variable "all-cidr" {}
variable "instance_type" {}
variable "port_ssh" {}
variable "port_sonar" {}
variable "port_proxy" {}
variable "port_http" {}
variable "port_https" {}
variable "port_nexus" {}
variable "port_mysql" {}
variable "red_hat" {}
variable "db-identifier" {}
variable "db-name" {}
variable "db-username" {}
variable "db-password" {}
variable "newrelic-license-key" {}
variable "newrelic-acct-id" {}
